language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - cp .env.tests .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql -u root -e "DROP DATABASE IF EXISTS lockd_tests;"
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS lockd_tests;"
  - php artisan migrate

script: vendor/bin/phpunit
